name: ci
on:
  push:
    branches: '*'
  pull_request:

jobs:
  test:
    name: Compile & Test
    strategy:
      matrix:
        go-version: ['1.25']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - uses: TimonVS/pr-labeler-action@v5.0.0
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run integration tests  
      run: make integration-test

    - name: Format code
      run: make format || true

    - name: Lint code
      run: make lint || true

    - name: Build binary
      run: make build
