name: ci
on:
  push:
    branches: '*'
  pull_request:

jobs:
  test:
    name: Compile & Test
    strategy:
      matrix:
        go-version: ['1.25']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run integration tests
      run: make integration-test

    - name: Format code
      run: make format || true

    - name: Lint code
      run: make lint || true

    - name: Build binary
      run: make build
