name: release
on:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          check-latest: true

      - name: Run integration tests
        run: make integration-test

      - name: Build all targets
        run: make all

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: ${{ contains(github.ref, '-') }}
          files: ./build/compiled/*
