name: snyk

on:
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@v1.0.0
      with:
        command: monitor
        args: --project-name=conntest
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
